services:
  mongodb:
    image: mongo:4.2
    profiles: [ "ved" ]
    volumes:
      - mongodb_data:/data/db
    networks:
      - graylog

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    profiles: [ "ved" ]
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 512m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - graylog

  graylog:
    image: graylog/graylog:4.3
    profiles: [ "ved" ]
    environment:
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9002/
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE=${GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE}
      - GRAYLOG_MESSAGE_JOURNAL_MAX_AGE=${GRAYLOG_MESSAGE_JOURNAL_MAX_AGE}
      - GRAYLOG_CONTENT_PACKS_AUTO_LOAD=${GRAYLOG_CONTENT_PACKS_AUTO_LOAD}
    networks:
      - graylog
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - 9000:9000
      - 12201:12201
      - 12201:12201/udp
    volumes:
      - graylog_data:/usr/share/graylog/data
      - graylog_journal:/usr/share/graylog/data/journal

networks:
  graylog:
    driver: bridge

volumes:
  mongodb_data:
  es_data:
  graylog_data:
  graylog_journal: