services:
  reverse_proxy:
    image: caddy:2.7.6
    container_name: reverse_proxy
    profiles: [ "ved" ]
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"  # Admin API port
    volumes:
      - ../reverse_proxy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - USE_HTTPS=${USE_HTTPS:-false}
      - EMAIL=${EMAIL:-}
    networks:
      - graylog
      - milvus
      - ved_network

networks:
  graylog:
    external: true
  milvus:
    external: true
  ved_network:
    external: true

volumes:
  caddy_data:
  caddy_config: